In [1]:
import numpy as np
from sklearn import preprocessing

# SAMPLE DATA

In [4]:
data = np.array([[2.1, -1.9, 5.5],
                [-1.5, 2.4, 3.5],
                [0.5 , -7.9, 5.6],
                [5.9 , 2.3 ,-5.8]])

data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [5]:
data.shape

(4, 3)

# 1 Binarisation

In [6]:
preprocessor = preprocessing.Binarizer(threshold=0.5)
data_binarisation = preprocessor.transform(data)

data_binarisation

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

# 2. Scalling

In [7]:
preprocessor= preprocessing.MinMaxScaler(feature_range=(0,1))
preprocessor.fit(data)
scalling_data = preprocessor.transform(data)
scalling_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

# 3. Normalisation

In [8]:
data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])