## transformers :

* Preprocessing
* Feature Extraction
* Imputation, etc

Method : 
* fit = akan membaca keseluruhan data dan akan membuat rumus untung scalling datanya
* Transform = mengubah data menjadi data yang udah di preproces <br>
cara cepat = fit_transform

In [3]:
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression

In [4]:
X, y = make_regression(n_samples=50, n_features=1, random_state=45, noise=5.0)

In [5]:
X

array([[-0.84134033],
       [ 0.22808162],
       [-0.42444883],
       [-1.00860081],
       [-1.54687318],
       [ 0.35430274],
       [ 2.24808957],
       [-0.62769549],
       [ 0.28968091],
       [ 0.25959597],
       [-0.44027617],
       [-0.01568471],
       [-0.49505193],
       [-0.1468827 ],
       [ 1.11098606],
       [-0.47439702],
       [-0.87330464],
       [-0.20430091],
       [-1.75075239],
       [-1.39381267],
       [-1.34025807],
       [-1.54136684],
       [ 0.02524419],
       [-2.59687863],
       [-0.12150685],
       [-0.93102638],
       [-0.60694397],
       [ 0.8019266 ],
       [-1.47331424],
       [ 0.67312896],
       [ 1.67029982],
       [-0.85418835],
       [ 0.02637477],
       [-1.4119755 ],
       [-1.65426275],
       [ 0.33263215],
       [-0.49954587],
       [ 1.27840959],
       [-0.30191524],
       [-0.55407712],
       [ 0.93510554],
       [-0.39514554],
       [ 0.39407266],
       [-0.65570411],
       [-1.27163265],
       [-0

### MinMaxScaler: Scale data dari 0 - 1 <br>
minimun scaler : 0 <br>
maximun scaler : 1 

In [7]:
from sklearn.preprocessing import  MinMaxScaler

In [8]:
Scalling = MinMaxScaler()

In [9]:
Scalling.fit(X)

,"feature_range feature_range: tuple (min, max), default=(0, 1)Desired range of transformed data.","(0, ...)"
,"copy copy: bool, default=TrueSet to False to perform inplace row normalization and avoid acopy (if the input is already a numpy array).",True
,"clip clip: bool, default=FalseSet to True to clip transformed values of held-out data toprovided `feature_range`.Since this parameter will clip values, `inverse_transform` may notbe able to restore the original data... note:: Setting `clip=True` does not prevent feature drift (a distribution shift between training and test data). The transformed values are clipped to the `feature_range`, which helps avoid unintended behavior in models sensitive to out-of-range inputs (e.g. linear models). Use with care, as clipping can distort the distribution of test data... versionadded:: 0.24",False


In [10]:
Scalling.data_min_ # data paling kecil

array([-2.59687863])

In [12]:
Scalling.data_max_ # data paling besar

array([2.24808957])

In [21]:
X_Scaled = Scalling.transform(X)
X_Scaled #cara liat data

array([[0.36234258],
       [0.58307096],
       [0.44838887],
       [0.32782007],
       [0.21672081],
       [0.60912296],
       [1.        ],
       [0.40643882],
       [0.59578503],
       [0.58957551],
       [0.44512211],
       [0.53275766],
       [0.43381641],
       [0.50567843],
       [0.76530217],
       [0.43807958],
       [0.35574516],
       [0.49382733],
       [0.17464021],
       [0.24831246],
       [0.25936611],
       [0.21785732],
       [0.54120537],
       [0.        ],
       [0.510916  ],
       [0.34383141],
       [0.41072192],
       [0.70151239],
       [0.23190336],
       [0.6749286 ],
       [0.88074437],
       [0.35969076],
       [0.54143872],
       [0.24456365],
       [0.19455564],
       [0.60465016],
       [0.43288886],
       [0.79985834],
       [0.47367976],
       [0.42163363],
       [0.72900049],
       [0.45443706],
       [0.61733146],
       [0.40065784],
       [0.27353038],
       [0.49684447],
       [0.48015213],
       [0.655