## KLASIFIKASI Menggunakan Metode Naive Bayes

## Import Library

In [54]:
import pandas as pd
import numpy as np


from sklearn.model_selection import train_test_split # <- spliting data / pembagian data
from sklearn.preprocessing import LabelEncoder #<- mengkonfersi data string menjadi label numrik
from sklearn.preprocessing import StandardScaler # <- mengsekala data numrik
from sklearn.naive_bayes import  GaussianNB # <- algoritma / Metode
from sklearn.metrics import confusion_matrix # <- menguji kinerja model
from sklearn.metrics import classification_report # <- evaluasi
from sklearn.metrics import  accuracy_score # <- evaluasi


## Baca Data

In [55]:
df_1 = pd.read_csv("dataset_customer_churn_label_string.csv")
df_1.head() #<- menampilkan 5 data taeratas

,customer_id,age,city,tenure_months,plan_type,monthly_bill,usage_hours,support_tickets,churn
0,1,56,Tangerang,52,Basic,428,76,14,Tidak Bertahan
1,2,38,Jakarta,24,Premium,210,57,5,Bertahan
2,3,19,Surabaya,30,Basic,373,68,1,Bertahan
3,4,38,Bandung,33,Basic,393,93,5,Bertahan
4,5,44,Tangerang,59,Basic,249,64,11,Bertahan


In [56]:
df_1.info() # <- mengatahui informasi terkait dataset

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      1000 non-null   int64
 1   age              1000 non-null   int64
 2   city             1000 non-null   str  
 3   tenure_months    1000 non-null   int64
 4   plan_type        1000 non-null   str  
 5   monthly_bill     1000 non-null   int64
 6   usage_hours      1000 non-null   int64
 7   support_tickets  1000 non-null   int64
 8   churn            1000 non-null   str  
dtypes: int64(6), str(3)
memory usage: 70.4 KB


In [57]:
df_1.empty # < - mengetahui apakah ada data kosong

False

### Process Label Encoding

ubah tipe data label yang tadinya str menjadi numrik

In [58]:
numrik = LabelEncoder() 

df_1['churn'] = numrik.fit_transform(df_1['churn'])

df_1['city'] = numrik.fit_transform(df_1['city'])

df_1['plan_type'] = numrik.fit_transform(df_1['plan_type'])
df_1.head()

,customer_id,age,city,tenure_months,plan_type,monthly_bill,usage_hours,support_tickets,churn
0,1,56,6,52,0,428,76,14,1
1,2,38,3,24,1,210,57,5,0
2,3,19,5,30,0,373,68,1,0
3,4,38,0,33,0,393,93,5,0
4,5,44,6,59,0,249,64,11,0


### Data sudah berubah dimana yagn tadinya string sekarang int

## Menetukan X dan Y

In [59]:
x = df_1.iloc[:, :-1].values
y = df_1.iloc[:, -1].values

In [60]:
x

array([[   1,   56,    6, ...,  428,   76,   14],
       [   2,   38,    3, ...,  210,   57,    5],
       [   3,   19,    5, ...,  373,   68,    1],
       ...,
       [ 998,   50,    4, ...,  460,   52,    5],
       [ 999,   44,    1, ...,  219,   65,   10],
       [1000,   48,    6, ...,  444,   39,   10]], shape=(1000, 8))

In [61]:
y

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,

### Spiliting Data


In [62]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=123)

print("X Train = ", len(x_train))
print("X Test = ", len(x_test))
print("Y Train = ", len(y_train))
print("Y Test = ", len(y_test))

X Train =  800
X Test =  200
Y Train =  800
Y Test =  200


### Pengskalaan Nilai

In [63]:
sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)


In [65]:
x_train

array([[ 0.0515938 ,  0.77912942, -0.03179685, ..., -0.44625829,
         1.40560439,  0.93090378],
       [ 0.65626661, -0.30840728, -0.03179685, ...,  0.92447328,
        -0.5260595 ,  1.38947707],
       [ 1.7467748 ,  0.63412453,  0.4669773 , ...,  1.38679103,
         0.02063782, -0.44481609],
       ...,
       [-0.40278462,  1.14164166,  0.4669773 , ..., -0.7058051 ,
        -1.40077523, -0.44481609],
       [-0.46220333,  0.19910985,  0.96575145, ..., -0.52736667,
         0.20287027,  1.16019043],
       [ 0.04460336,  0.34411474, -0.530571  , ...,  1.7031137 ,
        -0.34382706,  0.93090378]], shape=(800, 8))

In [66]:
x_test

array([[-1.26454394,  0.19530663,  1.44787362, ..., -1.43779388,
         0.65284993,  1.34919328],
       [-1.02338814, -1.68264172,  1.44787362, ...,  0.92524212,
        -0.43765663, -0.49113856],
       [-1.5358442 , -0.25540098,  1.44787362, ...,  0.82432955,
        -0.58305751,  0.19898588],
       ...,
       [ 0.4972331 ,  1.6976653 , -0.92568969, ...,  0.37863237,
         0.72555037, -0.72118004],
       [-0.99994244,  1.54742944, -0.92568969, ...,  1.04297345,
         0.94365168, -0.72118004],
       [-0.42719744,  1.6976653 , -1.40040236, ..., -0.87436537,
        -0.1832051 , -0.26109708]], shape=(200, 8))

In [68]:
y_train

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,

In [69]:
y_test


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0])

## Clasifikasi Model

In [71]:
klasifikasi = GaussianNB()

In [73]:
klasifikasi.fit(x_train, y_train)

,"priors priors: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
,"var_smoothing var_smoothing: float, default=1e-9Portion of the largest variance of all features that is added tovariances for calculation stability... versionadded:: 0.20",1e-09


In [75]:
y_predict = klasifikasi.predict(x_test)
y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0])

In [76]:
klasifikasi.predict_proba(x_test)

array([[9.74850112e-01, 2.51498882e-02],
       [8.11053127e-01, 1.88946873e-01],
       [7.26303615e-01, 2.73696385e-01],
       [9.22496088e-01, 7.75039123e-02],
       [9.57108956e-01, 4.28910437e-02],
       [9.39247043e-01, 6.07529567e-02],
       [9.09103924e-01, 9.08960756e-02],
       [9.97755827e-01, 2.24417294e-03],
       [9.85193147e-01, 1.48068527e-02],
       [7.20481759e-01, 2.79518241e-01],
       [9.83922497e-01, 1.60775034e-02],
       [9.89121648e-01, 1.08783517e-02],
       [9.49630940e-01, 5.03690600e-02],
       [9.95832028e-01, 4.16797200e-03],
       [9.29346164e-01, 7.06538362e-02],
       [9.78713037e-01, 2.12869626e-02],
       [8.86021710e-01, 1.13978290e-01],
       [9.30626118e-01, 6.93738825e-02],
       [9.84525311e-01, 1.54746892e-02],
       [9.90604859e-01, 9.39514104e-03],
       [4.87792440e-01, 5.12207560e-01],
       [9.86757512e-01, 1.32424876e-02],
       [9.93761999e-01, 6.23800118e-03],
       [9.44330148e-01, 5.56698521e-02],
       [5.293419

## EVALUASI

In [77]:
cm = confusion_matrix(y_test,y_predict)
print(cm)

[[174   1]
 [ 16   9]]


In [80]:
akurasi = classification_report(y_test, y_predict)
print(akurasi)

              precision    recall  f1-score   support

           0       0.92      0.99      0.95       175
           1       0.90      0.36      0.51        25

    accuracy                           0.92       200
   macro avg       0.91      0.68      0.73       200
weighted avg       0.91      0.92      0.90       200



In [82]:
akurasi = accuracy_score(y_test, y_predict)
print("Tingkat Akurasi : %d Persen"%(akurasi*100))

Tingkat Akurasi : 91 Persen
